spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/currency_converter
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8080

logging:
  level:
    root: INFO
    com.currency.converter: DEBUG
